# Generated by Django 4.2.2 on 2023-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='driver_details',
            field=models.CharField(max_length=122),
        ),
    ]
