# Generated by Django 4.2.2 on 2023-08-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_driver_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
