# Generated by Django 4.2.2 on 2023-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='schedule_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
