# Generated by Django 4.2.2 on 2023-08-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='driver_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driver'),
        ),
    ]
