# Generated by Django 4.2.2 on 2023-08-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_bin_driver_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.driver'),
        ),
    ]
