# Generated by Django 4.2.2 on 2023-08-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_complaint_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='complaint',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bin'),
        ),
    ]
