# Generated by Django 4.2.2 on 2023-08-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_complaint_driver_remove_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed')], default='not_completed', max_length=20),
        ),
    ]
