# Generated by Django 4.2.2 on 2023-08-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_complaint_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
