# Generated by Django 4.2.2 on 2023-08-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
