# Generated by Django 4.2.2 on 2023-08-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_admin_id_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='admin_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.admin'),
        ),
    ]
