# Generated by Django 4.2.2 on 2023-08-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_bin_admin_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='average_rating1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='average_rating2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='average_rating3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
