# Generated by Django 4.2.2 on 2023-08-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_feedback_average_rating1_feedback_average_rating2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='average_rating1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='average_rating2',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='average_rating3',
        ),
    ]
