# Generated by Django 4.2.2 on 2023-08-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_delivery_latitude_delivery_locality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='longitude',
        ),
    ]
