# Generated by Django 4.2.2 on 2023-08-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_delivery_latitude_remove_delivery_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
