# Generated by Django 4.2.2 on 2023-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_complaint_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ananda',
            fields=[
                ('username', models.CharField(max_length=122, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=33, unique=True)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
